# Generated by Django 5.2.8 on 2025-11-26 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='original_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('bouquet', 'Готовые букеты'), ('single', 'Цветы поштучно'), ('box', 'Цветы в коробке'), ('plant', 'Комнатные растения'), ('gift', 'Подарки'), ('sale', 'Акции'), ('seasonal', 'Сезонные')], max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='occasion',
            field=models.CharField(blank=True, choices=[('birthday', 'День рождения'), ('love', 'Любовь/Романтика'), ('wedding', 'Свадьба'), ('anniversary', 'Юбилей'), ('sorry', 'Извинения'), ('congrats', 'Поздравления'), ('universal', 'Универсальный'), ('spring', 'Весна'), ('luxury', 'Роскошь'), ('date', 'Свидание'), ('new_year', 'Новый год'), ('surprise', 'Сюрприз'), ('home', 'Дом'), ('office', 'Офис'), ('man', 'Мужчине'), ('relax', 'Релакс'), ('autumn', 'Осень')], max_length=20),
        ),
    ]
