# Generated by Django 5.2.8 on 2025-12-10 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_product_original_price_alter_product_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomBouquetRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occasion', models.CharField(max_length=100, verbose_name='Повод')),
                ('preferred_flowers', models.CharField(max_length=200, verbose_name='Предпочтительные цветы')),
                ('color_scheme', models.CharField(max_length=100, verbose_name='Цветовая гамма')),
                ('budget', models.IntegerField(verbose_name='Бюджет')),
                ('wishes', models.TextField(verbose_name='Пожелания')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='Имя')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('status', models.CharField(choices=[('новая', 'Новая'), ('обработана', 'Обработана'), ('в работе', 'В работе')], default='новая', max_length=50, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Заявка на авторский букет',
                'verbose_name_plural': 'Заявки на авторские букеты',
                'ordering': ['-created_at'],
            },
        ),
    ]
